### ISSUE TITLE
login options

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-cli#1]
I'd like to be able to `captainduckduck login` as part of a script I run to set up a new server (* edit... see below).  Is it possible to supply command-line options to `login` to specify all the required information without prompting?  If not, would that be something that could be added in future?

This is actually for deploying an IDE app, with captainduckduck installed inside the IDE container.  Maybe it's enough that I can just persist the `~/.config` folder of the IDE app between deploys (using a persistent directory), so that at least the server info and captain machine name is remembered... I don't mind having just to enter a fresh password the first time I do a `captainduckduck deploy` after re-deploying the IDE app... I just don't want to have to have to re-enter *all* captain machine details again.

EDIT: I have tried persisting the `~/.config` folder, and confirm that it works as intended.  Probably that's better than starting from scratch and auto-logging in after re-deploying, because you retain all the various captain defaults, from previous deploys, that have been built up over time.

**Comment by githubsaturn** [comment]
Done in v1.2.0
https://github.com/caprover/caprover-cli#login
