### ISSUE TITLE
Using deploy -d without defaults doesn't work first time

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-cli#10]
If I run `caprover deploy -d` for an app which hasn't yet been deployed (i.e. no defaults yet), it helpfully starts asking me how I want to deal with it... first choose the machine, then choose what branch.  If I hit Enter for the "branch" question, the deploy process just quits back to the command line without getting to the next question.  I have to run deploy again, which starts back at the first question but this time asks me all questions and then continues OK with the deploy.  Minor issue, but would be nice to fix.

**Comment by githubsaturn** [comment]
Fixed in https://github.com/caprover/caprover-cli/commit/9558727fbf8388717deaa66697387e11ec81a65b

Will be in the next release.
