### ISSUE TITLE
How to make a docker run

### ISSUE THREAD

**Issue by nixilb** [caprover/caprover-cli#100]
Hello,

I want to use CapRover to install this nodeJS app: I usually use

docker run -it -p 1990:1880 --name mybot 6v099815.gra5.container-registry.ovh.net/nis/nodered-git-login:v4

An idea?

**Comment by githubsaturn** [comment]
- Create a new app
- Go to HTTP settings of your app, change the container HTTP port to 1880
- Click on SAVE and UPDATE
- Go to deployment tab, one of the methods is "image deploy", enter this image's name and click on deploy. `mybot 6v099815.gra5.container-registry.ovh.net/nis/nodered-git-login:v4`


Note: if your docker registry is private, make sure you first connect your docker registry:
- Go to cluster tab
- Add new remote registry
- Enter your registry info 6v099815.gra5.container-registry.ovh.net......
- Save
- Change the `default push` to `disabled` [IMPORTANT}

**Comment by nixilb** [comment]
This docker images contains an IBM NodeRED. 
Do you think I will be able to access its API entry point using https?

**Comment by githubsaturn** [comment]
As long as it exposes an HTTP port on 1880, yes.

**Comment by nixilb** [comment]
Were do I put parameters of the docker run command?

**Comment by githubsaturn** [comment]
CapRover uses docker swarm. You don't deploy containers, you deploy services. 

Only a handful of flags are available on the UI. Env vars, ports and image. 


Always restart is not needed. Docker swarm automatically does that.

**Comment by nixilb** [comment]
Now it works perfectly. I now have an API written in nodeRED that I can access using https in a much simpler way than what is described in the NodeRED documentation.
Also awesome support.
