### ISSUE TITLE
Failed to deploy Mosquitto as OneClick App

### ISSUE THREAD

**Issue by nixilb** [caprover/caprover-cli#101]
see screen dumps
![image](https://user-images.githubusercontent.com/64604304/125085447-e1b9d500-e0ca-11eb-8272-b16035ba1f6d.png)

**Comment by githubsaturn** [comment]
This is failing because it fails to push the image to your registry. You don't need registry for one click apps. Do this:
- Go to cluster tab
- Disable default push to disable (you can click on the light red text)
- Try again to deploy your mosquitto and it'll go through.

**Comment by nixilb** [comment]
Works:
But in the log:
"Starting in local only mode. Connections will only be possible from clients running on this machine."
How to open to non localhost clients?

**Comment by githubsaturn** [comment]
This is a question for their maintainers. At this point the app is deployed and CapRover is out of the loop.
