### ISSUE TITLE
Docker Hub has old version

### ISSUE THREAD

**Issue by iBobik** [caprover/caprover-cli#106]
Using CLI in a GitLab CI where it is fetched from Docker Hub, where is 2 months old version (no app tokens).

Could you setup automated deployment to Docker Hub?

https://hub.docker.com/r/caprover/cli-caprover

**Comment by githubsaturn** [comment]
Thanks for the report. We used to have automated deployment on Docker Hub, but looks like they've changed it to be a paid option starting a few weeks ago. 

I'll change the workflow to use github's pipeline to build the image soon.

**Comment by githubsaturn** [comment]
Updated: https://hub.docker.com/r/caprover/cli-caprover/tags?page=1&ordering=last_updated

**Comment by iBobik** [comment]
Thank you for a quick update.

Honza Pobořil
