### ISSUE TITLE
Caprover stateless deploy command fails on Gitlab CI Pipeline

### ISSUE THREAD

**Issue by JacobSamro** [caprover/caprover-cli#11]
Caprover stateless deploy fails on Gitlab CI Pipeline. This is working normally when I ran the command locally. I am using a `node:8.15.1` image 

```shell
$ caprover deploy -h https://domain.com -p pass -b dev -a staging-app
Preparing deployment to Captain...

**** Warning **** No captain-definition was found in main directory. Falling back to Dockerfile.
Saving tar file to:
/builds/Projects/App-Project/temporary-captain-to-deploy.tar

TAR file failed
Error: Command failed: git archive --format tar --output "/builds/Projects/App-Project/temporary-captain-to-deploy.tar" dev
fatal: Not a valid object name

TAR file failed
```

Possibility it might be related to git. Git version `2.11.0` was already installed there.

**Comment by githubsaturn** [comment]
I think during checkout process gitlab removes .git directory. Check to see if this is true by running `ls` before deploy. 

If that's the case you can manually create tar file and use direct tar file method.

**Comment by githubsaturn** [comment]
Have a look at this for an example usage of direct tar file upload:
https://caprover.com/docs/recipe-deploy-create-react-app.html

**Comment by JacobSamro** [comment]
Great !. Thank you 💯

**Comment by JacobSamro** [comment]
I solved it by following steps

1. Create tar file
```shell
tar -cvf ./deploy.tar .
```
2. Upload to Caprover
```shell
caprover deploy -t ./deploy.tar -h https://domain.com -p pass -a staging-app
```
