### ISSUE TITLE
Where is the configuration file stored?

### ISSUE THREAD

**Issue by fishnux** [caprover/caprover-cli#112]
Hello,

Where is the configuration file stored by default?

**Comment by githubsaturn** [comment]
CapRover uses [Configstore](https://github.com/yeoman/configstore#readme) and that package takes care of finding a proper location for the config file depending on your OS.

https://github.com/caprover/caprover-cli/blob/d20488cf70c956b92e051c09320741fcb6bc62af/src/utils/StorageHelper.ts#L24-L26
