### ISSUE TITLE
Stuck in the middle when entering 2nd bad password in serversetup

### ISSUE THREAD

**Issue by nixilb** [caprover/caprover-cli#116]
serversetup failed because the second password was not the same as the first one.
As is is HIDDEN I had no chance to now what the first one was.

Now I'm stuck:

> e:\>caprover serversetup
> 
> 
> Setup CapRover machine on your server...
> 
> ? have you already started CapRover container on your server? Yes
> ? IP address of your server: xxx
> 
> You may have already setup the server with root domain: vps-roro.ovh! Use caprover login to log into an existing server.
> 

The caprover login in another nightmare.
I want to go back. where is the state to delete?

Tried in C:\Users\nisju\.config\configstore but failed.

I just want to rollback to the state before.

By the way: there is NO PIRATES behind me in my room.

**Comment by githubsaturn** [comment]
What's the issue with CapRover Login?

**Comment by nixilb** [comment]
serversetup failed because the second password was not the same as the first one.
I didn't say it was configured.
(for instance I didn't get the opportunity to enter the email address to get certificate and enable HTTPS)

**Comment by nixilb** [comment]
Is it possible to avoid:
docker service rm $(docker service ls -q)

## remove CapRover settings directory
rm -rf /captain
docker swarm leave --force

**Comment by githubsaturn** [comment]
If `serversetup` exits before you enable HTTPs, you can always run `serversetup` again.

**Comment by nixilb** [comment]
yes, but is stops saying:

> You may have already setup the server with root domain: vps-roro.ovh! Use caprover login to log into an existing server.

even if it did'nt end correctly

**Comment by githubsaturn** [comment]
Okay, so just login to your dashboard via web: `captain.yourrootdomain.com` and just user `captain42` as password. 

Then click on ENABLE HTTPS > enter email 
Then click on FORCE HTTPS

Then run `caprover login` on your local machine

**Comment by nixilb** [comment]
captain.yourrootdomain.com:3000 I suppose

**Comment by githubsaturn** [comment]
yes, but you don't need :3000 probably

**Comment by nixilb** [comment]
Done (the port was needed). I suppose it fixed the HTTPS part.
I worry about the badly entered password it asked twice.
And what about the CapRover machine name, with whom the login credentials are stored locally ? I hadn't the opportunity to enter it

**Comment by githubsaturn** [comment]
You can use `caprover login` and save the credentials locally

**Comment by nixilb** [comment]
what is it for (local credentials)?

**Comment by githubsaturn** [comment]
When you want to run `caprover deploy` it uses those creds.

**Comment by nixilb** [comment]
Login fails (may be because the password I was not able to enter fails?):

> e:\>caprover login
> Login to a CapRover machine...
> 
> ? CapRover machine URL address, it is "[http[s]://][captain.]your-captain-root.domain": http://captain.vps-roro.ovh
> ? CapRover machine password: [hidden]
> ? CapRover machine name, with whom the login credentials are stored locally: fidji
> 
> Something bad happened: cannot save fidji at http://captain.vps-roro.ovh.
> 302 - undefined

**Comment by githubsaturn** [comment]
For your root domain enter https if you've enabled HTTPS

**Comment by nixilb** [comment]
I was able to login using captain42 as a password:

> Login to a CapRover machine...
> 
> ? CapRover machine URL address, it is "[http[s]://][captain.]your-captain-root.domain": https://captain.vps-roro.ovh
> ? CapRover machine password: [hidden]
> ? CapRover machine name, with whom the login credentials are stored locally: fidji
> 
> Logged in successfully.
> Authorization token is now saved as fidji at https://captain.vps-roro.ovh.

And now does C:\Users\nisju\.config\configstore\caprover.json exist.

How to change psw?

**Comment by nixilb** [comment]
I changed password in the dashboard. I can now connect to the dashboard to the new one.
Now I suppose the auth part in C:\Users\nisju.config\configstore\caprover.json is wrong.
Should I caprover login again with the new password?

**Comment by githubsaturn** [comment]
Yes. You can first logout, then log in using the new password.

**Comment by nixilb** [comment]
Done.
Do you think everything is ok now?

**Comment by nixilb** [comment]
Merci +++.
(awesome support)
