### ISSUE TITLE
Confusing dashboard button aspect

### ISSUE THREAD

**Issue by nixilb** [caprover/caprover-cli#117]
Button are flashy blue when OFF and greyed when ON.

This is very confusing as it should be the opposite.

Particular pb is the "enable HTTPS" which looks at ON at first look although it was OFF. Very difficult to fix.

**Comment by githubsaturn** [comment]
Not sure what you mean. Buttons are blue when they are primary actions, they are greyed out when they are disabled.

**Comment by githubsaturn** [comment]
Example here where HTTPs has been enabled, therefore the button is now disabled.

![image](https://user-images.githubusercontent.com/10582082/158077834-a78cd1c7-d400-4e8f-afe9-c7cceb0b30eb.png)

**Comment by nixilb** [comment]
This is an checked option, but it looks like a dimmed one:

![Capture](https://user-images.githubusercontent.com/64604304/158079653-9f88ef33-5c47-4adb-907d-414dfa5f0399.PNG)

When unchecked, it is flashy blue looking as a checked one (but it is not)

**Comment by githubsaturn** [comment]
Ah I see. yea, it's not unchecked, the button is disabled.

**Comment by nixilb** [comment]
When unchecked, it is flashy blue looking as a checked one (but it is not).

This one is unchecked:

![Capture](https://user-images.githubusercontent.com/64604304/158082247-4f524724-685b-4a3e-bde7-57a8d014b03a.PNG)
