### ISSUE TITLE
Error: manifest for node:18.00-alpine not found

### ISSUE THREAD

**Issue by minamme** [caprover/caprover-cli#124]
I'm trying to deploy app but seeing following error:
```bash
Saving tar file to: "/home/minam/web/api/temporary-captain-to-deploy.tar"
Using last commit on "master": 730c6eddc0407431ad64b5bcff7acf431c509262

Deploying scraper to captain-01...

Uploading [====================] 100%  (ETA 0.0s)
Upload done.

This might take several minutes. PLEASE BE PATIENT...

Building your source code...

------------------------- Sun Jun 12 2022 14:14:16 GMT+0000 (Coordinated Universal Time)
Build started for scraper
Ignore warnings for unconsumed build-args if there is any
Step 1/11 : FROM library/node:18.00-alpine

{"message":"manifest for node:18.00-alpine not found: manifest unknown: manifest unknown"}
manifest for node:18.00-alpine not found: manifest unknown: manifest unknown
Build has failed!
----------------------
Deploy failed!
Error: {"message":"manifest for node:18.00-alpine not found: manifest unknown: manifest unknown"}
manifest for node:18.00-alpine not found: manifest unknown: manifest unknown

Something bad happened. Cannot deploy scraper at captain-01.
```
**Note**
- I tried changing `templateId` but it still shows `node:18.00-apline` while I tried `node/16.0.0`. I think it's cached :confused: 
- Other apps and sample apps are working fine

Development OS: Linux Mint
Deploy server: Vultr high performance VPS.

**Comment by githubsaturn** [comment]
You changed your templateId but you probably didn't commit the change. Make sure to commit the change so that it get picked up by CapRover.

Regarding `node:18.00`, the error is completely expected. There is no such a version, what you want is `18`, not `18.00`

See here: https://hub.docker.com/_/node

**Comment by minamme** [comment]
Thanks. I am new to caprover that's why don't know this
