### ISSUE TITLE
Something bad happened during authentication

### ISSUE THREAD

**Issue by Jenbai22** [caprover/caprover-cli#130]
When trying to deploy our project on gitlab we get an error stating something bad happened during authentication. [
![Screenshot 2023-01-26 at 12 50 19 PM](https://user-images.githubusercontent.com/111788281/214911120-1c3bc5a9-70eb-42c5-8e24-3cd63f4a7772.png)
](url)

**Comment by githubsaturn** [comment]
You're probably changed your root domain. 

http://captain.ripe-tomatoes.sept-ct-5.mod3projects.com/

Does not show a caprover dashboard.
