### ISSUE TITLE
Fetching build logs when using app access token

### ISSUE THREAD

**Issue by MihailRussu** [caprover/caprover-cli#136]
Is there any reason for [this snippet](https://github.com/caprover/caprover-cli/blob/master/src/utils/DeployHelper.ts#L86C17-L94):
```ts
            if (machineToDeploy.appToken) {
                StdOutUtil.printMessage(
                    `Deploying ${StdOutUtil.getColoredAppName(
                        appName
                    )} using app token is in progress. Build logs aren't retrieved when using app token.\nWait a few minutes until your app is built and deployed`
                )
            } else {
                this.startFetchingBuildLogs(machineToDeploy, appName)
            }
```
?

It would likely be more secure to disclose just an individual app access token in the CI/CD, rather than the global CapRover instance password, but then one would be missing out on the build logs (the primary reason to use the cli in the first place).

Assuming build logs are not available for app access tokens - is there a chance that decision could be reconsidered?

**Comment by githubsaturn** [comment]
The block you posted is on the CLI client code. The main problem is that the endpoint for fetching logs need to whitelisted.

Even if you change the block above, it's not going to have any impact on the output, You will just see an error.

**Comment by githubsaturn** [comment]
Feel free to open a feature request to whitelist the build logs using the app access token.
