### ISSUE TITLE
Is it possible to use --caproverUrl without domain ?

### ISSUE THREAD

**Issue by djiworks** [caprover/caprover-cli#139]
Hi everyone !

First of all, thank you for this awesome project. I mean it's a very useful tech for any developers !

I'm trying to install caprover and I know that in a normal usage we have to setup the domain name before deploying apps.

But let's say I want to run `docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl="http://<my-ip>:3000" # other args`

Is that possible ? Because I have noticed that cli always return captain. as subdomain. e.g `http://<my-ip>:3000 to http://captain.<my-ip>`

My goal is just to be able to deploy some apps even if they will not be accessible until domain is setup (nginx reverse proxy job).

**Comment by githubsaturn** [comment]
Thanks for the kind words! :) 


Regarding the question: even if it works, it's not what the CLI is designed for, so you may end up facing issues.

If your goal is to deploy apps without having them being accessible, you can simply achieve this by checking this checkbox:

![image](https://github.com/caprover/caprover-cli/assets/10582082/82c8222b-4bae-488a-9823-a0f47826e23d)
