### ISSUE TITLE
CLI receives a 405 in CI environment

### ISSUE THREAD

**Issue by Ked57** [caprover/caprover-cli#18]
Hello there, I've been trying to deploy my app with CircleCI and this CLI. Basically this command doesn't work:

> caprover deploy -h $DOMAIN -p $PASSWORD -b master -a $APPNAME

it throws 
 
> #!/bin/bash -eo pipefail
> caprover deploy -h $DOMAIN -p $PASSWORD -b master -a $APPNAME
> 
> Preparing deployment to Captain...
> 
> (node:71) UnhandledPromiseRejectionWarning: StatusCodeError: 405 - ""
>     at new StatusCodeError (/usr/local/lib/node_modules/caprover/node_modules/request-promise-core/lib/errors.js:32:15)
>     at Request.plumbing.callback (/usr/local/lib/node_modules/caprover/node_modules/request-promise-core/lib/plumbing.js:104:33)
>     at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/caprover/node_modules/request-promise-core/lib/plumbing.js:46:31)
>     at Request.self.callback (/usr/local/lib/node_modules/caprover/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:198:13)
>     at Request.<anonymous> (/usr/local/lib/node_modules/caprover/node_modules/request/request.js:1161:10)
>     at Request.emit (events.js:198:13)
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/caprover/node_modules/request/request.js:1083:12)
>     at Object.onceWrapper (events.js:286:20)
>     at IncomingMessage.emit (events.js:203:15)
>     at endReadableNT (_stream_readable.js:1129:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:71) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:71) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'm not sure if this is a bug or if I am doing something wrong

**Comment by githubsaturn** [comment]
Are you able to reproduce the issue on a local machine?

My guess is there's a typo in your domain variable.

**Comment by Ked57** [comment]
yes, same error on the local machine. 

I found my mistake tho, i was using the app.mydomain.com instead of captain.mydomain.com

Thanks for the help  😄
