### ISSUE TITLE
Create an app using only the CLI

### ISSUE THREAD

**Issue by fr3fou** [caprover/caprover-cli#22]
When using `caprover deploy` it only gives you the option use an already existing app. 

I propse a new prompt is added while deploying to create an app right from the CLI, it would make the entire process much less troublesome and faster.

**Comment by githubsaturn** [comment]
Please see the discussion here: https://github.com/caprover/caprover-cli/issues/12

Short version: 
> The reason is that CapRover has a relatively large API, not all API methods are implemented in CLI. It'll be a maintenance nightmare to have a CLI command for each API endpoint. We kept the CLI commands limited to most common ones.

However, we now have a generic API subcommand, this lets you call any endpoint and customize based on your specific needs. https://github.com/caprover/caprover-cli#api
