### ISSUE TITLE
DNS Record Issue

### ISSUE THREAD

**Issue by synetalsolutions** [caprover/caprover-cli#29]
I have created A record on my server like server.domain.com but when i try to run run **caprover serversetup** it show error like 

> Double check your DNS, if everything looks correct note that DNS changes take up to 24 hours to work properly. Check with your Domain Provider.
> 
> Error Code: 1107  Message: Verification Failed.

However i am able to ping the server.domain.com and it resolving don't know why it creating this issue..

**Comment by githubsaturn** [comment]
You should create a wild card entry, like `*.server.domain.com` not a concrete entry like  `server.domain.com`.

After creating a wildcard entry, you can check via checking the IP for `anything.server.domain.com`

**Comment by synetalsolutions** [comment]
> You should create a wild card entry, like `*.server.domain.com` not a concrete entry like `server.domain.com`.
> 
> After creating a wildcard entry, you can check via checking the IP for `anything.server.domain.com`

I am using cloudflare for DNS records without proxy when i try to add *. it says invalid domain...

**Comment by synetalsolutions** [comment]
> > You should create a wild card entry, like `*.server.domain.com` not a concrete entry like `server.domain.com`.
> > After creating a wildcard entry, you can check via checking the IP for `anything.server.domain.com`
> 
> I am using cloudflare for DNS records without proxy when i try to add *. it says invalid domain...

ok that worked for me it was not working before thanks for quick support.
