### ISSUE TITLE
Running serversetup again should not try to setup an existing server

### ISSUE THREAD

**Issue by solomon23** [caprover/caprover-cli#31]
If you run serversetup against an existing server - it should check and not try to setup SSL again. Ref #30

**Comment by Hazzard17h** [comment]
If you run `serversetup` against an existing server with root ssl and redirect (setupped from CLI), it warns with "You may have already setup the server! Use caprover login to log into an existing server.", and fails with an error.

**Comment by solomon23** [comment]
In my case i ran `serversetup` against an existing server that I never setup with the CLI.  The SSL was already setup though and it asked to set it up again.

**Comment by Hazzard17h** [comment]
Maybe the http -> https redirect is not enabled, otherwise it should warn as I said, even if it is not setupped from the CLI.

**Comment by githubsaturn** [comment]
I believe there's a way for us to detect the existing installation if "force HTTPS" isn't activated. We can do so by getting the existing root domain of the installation. If the root domain is the default one, we know it's a fresh installation, otherwise it's an existing installation.

**Comment by solomon23** [comment]
> Maybe the http -> https redirect is not enabled, otherwise it should warn as I said, even if it is not setupped from the CLI.

Correct - I never enabled that

**Comment by Hazzard17h** [comment]
See [here](https://github.com/caprover/caprover-cli/pull/33/commits/f4112588b28b039b217a135ff24ce4f55642f9f5)
Needs to be tested @solomon23

**Comment by solomon23** [comment]
Confirmed it fixes it

**Comment by githubsaturn** [comment]
Fixed in https://github.com/caprover/caprover-cli/pull/33 and released as 2.1.0
