### ISSUE TITLE
Server setup fails on Enabling SSL with 404

### ISSUE THREAD

**Issue by lgraubner** [caprover/caprover-cli#34]
I have a server running the caprover docker container and an root domain like `captain.api.my.domainname.com` with an A record `*.captain.api.my.domainname.com` pointing to my server.
I can access the dashboard and login.

Whenever I'm trying to run `caprover serversetup` it fails on "Enabling SSL" with `Error: StatusCodeError: 404 - "<!doctype html>\n<html>\n\n<head>`...

So basically the html output of the default page. What am I doing wrong? DNS is properly propagated.

**Comment by danielivert** [comment]
Hello,

Do you also experience issues by setting up the server using the GUI instead of the CLI?

**Comment by lgraubner** [comment]
I was able to enable HTTPS without any problems from the Dashboard.

**Comment by lgraubner** [comment]
Oh by the way: I'm using Ubuntu 18.04 as 16.04 already reached end of life.

**Comment by githubsaturn** [comment]
Fixed in https://github.com/caprover/caprover-cli/pull/33 and released as 2.1.0
