### ISSUE TITLE
Failed deploy exits with code 0, causing CI to succeed

### ISSUE THREAD

**Issue by panta82** [caprover/caprover-cli#35]
```
script:
    - npm i caprover -g
    - caprover deploy -h "$CAPROVER_PRODUCTION_HOST" -p "$CAPROVER_PRODUCTION_PASS" -i "$DOCKER_REGISTRY/image-name:${CI_COMMIT_SHA:0:8}" -a image-name
```

![image](https://user-images.githubusercontent.com/4291324/65510804-12b91d80-ded6-11e9-9c61-5d6e13f31010.png)

Even though the deploy fails, caprover-cli exits with code 0. So CI reports success.

**Comment by githubsaturn** [comment]
Fixed in https://github.com/caprover/caprover-cli/pull/33 and released as 2.1.0
