### ISSUE TITLE
Deploy with custom admin domain url

### ISSUE THREAD

**Issue by losadaem** [caprover/caprover-cli#39]
I would like to deploy to a custom URL `http://<IP-ADDRESS-OF-SERVER>:3000` because of a local installation inside a local network without using domain names. Similar to the setup explained in https://github.com/caprover/caprover/issues/246.

But right now the cli is cleaning the url with `cleanAdminDomainUrl`, adding the `ADMIN_DOMAIN` by default and getting rip off the port. 

Is there a way around it ? Thank you so much.

**Comment by githubsaturn** [comment]
Local installations are meant to be used for testing and evaluation purposes. In those case, you don't generally need CLI.

But if you have a complex installation where the CapRover is installed on a local network, you can use a local DNS server that points a custom domain to the machine that hosts your CapRover instance. You can use `mycaproverinstallation.localhost` as your domain, by default this domain resolves to 127.0.0.1. Or if you want to connect to your CapRover instance from another machine, you need to have a DNS server on your network such that on ALL MACHINES on the network, `*.domain.mynetwork` resolves to the IP address of the machine that hosts CapRover.

**Comment by losadaem** [comment]
In this case I'm not able to configure the DNS server for subdomains. Everything works fine without the need of the DNS server right now. I'm only patching the CLI to skip the `cleanAdminDomainUrl` and it works like a charm. Thanks for your work, it's awesome.

Only as a suggestion. If the user passes a full Url including the port and everything why not use that  instead of the default values.
