### ISSUE TITLE
Add --image options for deploy command

### ISSUE THREAD

**Issue by m0xx** [caprover/caprover-cli#4]
As discussed [here](https://github.com/caprover/caprover/issues/360#issuecomment-460105643) we could had the possibility to deploy directly a new image by specifying the new tag in the deploy command.

The proposed solution:

```caprover deploy -h https://captain.root.domain.com -p password  -a app-name --image private.registry.com/username/new-image:version``` 

It would call the endpoint `/api/v2/user/apps/appData/your-app-name-here` with the correct payload.

Let me knows when it will be available in a version I can test, I will write a tutorial to build a new image, test it and deploy it to Caprover with CircleCI

**Comment by githubsaturn** [comment]
Done in v1.1.0

To update:
```
npm i -g caprover
```
or
```
sudo npm i -g caprover
```

**Comment by githubsaturn** [comment]
@m0xx 

I've tested this with simple images (public repo) and it worked. Please let me know if you face any issues from private repos.

**Comment by githubsaturn** [comment]
Also, looking forward to seeing your tutorial :)

**Comment by hjalle** [comment]
Worked fine for me using ACR

**Comment by osmanzeki** [comment]
For anyone else that gets an error like `error: unknown option --image`. You actually need to use the `--imageName` option instead of `--image`.

Like so:

```bash
caprover deploy -h https://captain.root.domain.com -p password -a app-name --imageName private.registry.com/username/new-image:version
```

**Comment by charleshan** [comment]
We should include this in the docs.

https://caprover.com/docs/cli-commands.html
