### ISSUE TITLE
[Suggestion] If there is no captain-definition but a Dockerfile, simply use that

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [caprover/caprover-cli#42]
Just a minor thing I came across since I'm up to running almost 10 projects with CapRover and keep finding myself just copy-pasting that essentially empty `captain-definition` file. Which made me wonder whether that might not be a relatively common use case.

(I don't use `dockerfileLines` because I like syntax highlighting and automatic indentation.)

**Comment by githubsaturn** [comment]
This should be the case currently:
https://github.com/caprover/caprover-cli/blob/master/src/utils/ValidationsHandler.ts#L30-L35

Is it not working for you?

**Comment by s-h-a-d-o-w** [comment]
Damn, it does. 😅

Maybe I'm wrong about this as well but I don't think that that is mentioned in the docs? Because I'm going to go with that that's the reason why I never even tried it. 😉

Anyway, thanks and awesome that that works, makes everything a bit tidier! 👍
