### ISSUE TITLE
caprover deploy outputs nothing after selecting branch

### ISSUE THREAD

**Issue by ekersten** [caprover/caprover-cli#49]
I select the machine, then the app name and after the branch is selected caprover just sits there with no output whatsoever. 

This is a fresh install on DigitalOcean using the marketplace app and the updated to 1.6.1.

CLI version is 2.1.1

This happens with all the sample apps. I've even tried deploying via TAR file, with no success.

One-click-apps like MySQL and PhpMyAdmin work great.

Any insights on the root of this issue?

**Comment by githubsaturn** [comment]
Are you running on windows terminal? If so, can you please try a different terminal, like bash?

**Comment by ekersten** [comment]
@githubsaturn this issue is a duplicate for #40. Feel free to close/delete
