### ISSUE TITLE
Deploy command with--default argument 

### ISSUE THREAD

**Issue by digiology** [caprover/caprover-cli#51]
When running the deploy command with --default on a newly created app, the cli throws an error 

"xxxxxx app not exist on this CapRover machine." 

Where xxxxx is a previously deleted app of a different name. 

Removing the --default argument solves it.

**Comment by githubsaturn** [comment]
Can you please provide a step by step reproducible scenario? Like
1- Create a new app on CapRover named "new-app-1"
2- ....

**Comment by githubsaturn** [comment]
This turned out to be a non issue. CapRover uses the directory to map the previous deploy. If the directly was mapped to another app, `--default` would try to deploy to that app.
