### ISSUE TITLE
Add option to skip logging build status during deploy

### ISSUE THREAD

**Issue by marhaupe** [caprover/caprover-cli#54]
As far as I can tell by skimming the source, running `caprover deploy` with only a Dockerfile in my repo will upload my application and then build my Docker image on my caprover instance. The build logs that are being printed are from the remote server and not from the environment my `caprover deploy` command is running from. Am I right?

If that's the case, I'd propose a flag that lets me skip the part where I'm seeing the build logs. If the flag is set, the deploy command could just exit after uploading the application. For people that test and deploy their application in a CI environment that is billed by the minute this would save time and thus money. What do you think?

**Comment by githubsaturn** [comment]
This is really simply to do with bash. There is no need to pollute the api:
```
caprover deploy --default 2>&1 | sed -e '/This might take several minutes/q'
```

As soon as `This might take several minutes` appears in log, the process will exit.

**Comment by marhaupe** [comment]
Well that's easy. I should really work on my bash skills. Thanks alot! Great work on caprover by the way, it's making my life so much easier
