### ISSUE TITLE
Create new app via API call: what is "detached"?  plus other questions...

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-cli#55]
I'm trying to create a new app via the CLI (or rather in a script), and see that I need to use a custom api call, as explained [here](https://github.com/caprover/caprover-cli/issues/22) and [here](https://github.com/caprover/caprover-cli/issues/12).

When looking [here](https://github.com/caprover/caprover-frontend/blob/master/src/api/ApiManager.ts) for the right parameters to pass, I think it is the `registerNewApp()` method that is relevant.  But what does the `detached` query string part mean?

What I have so far is:

    CAPROVER_PWD="notmypassword"
    CAPROVER_ROOT_DOMAIN="myserver.domain.com"
    CAPROVER_API_PATH="/user/apps/appDefinitions/register"
    CAPROVER_API_METHOD="POST"
    CAPROVER_APP_NAME="mynewapp"
    CAPROVER_API_DATA="{\"appName\":\"${CAPROVER_APP_NAME}\",\"hasPersistentData\":true}"
    caprover api --caproverUrl "https://captain.${CAPROVER_ROOT_DOMAIN}" --caproverPassword "${CAPROVER_PWD}" --path "${CAPROVER_API_PATH}" --method "${CAPROVER_API_METHOD}" --data "${CAPROVER_API_DATA}"

Is the above correct so far, and does the path need to include `?detached=1`?

The app I am trying to create has persistent data... I'm specifying that already above via the `data` argument.

But the app also needs:

- custom port mapping (server 8080, container 8080)
- env vars
- possibly custom persistent directory mappings (possibly not)
- `Websocket Support` enabled

How do I set those up via the `caprover api` call?

**Comment by githubsaturn** [comment]
detached means that the HTTP call returns as soon as CapRover engines receives the http call. Not passing `detached` causes the HTTP call to wait until the app is successfully created and setup before returning the HTTP call.


Clicking on Update and Save calls this method:
https://github.com/caprover/caprover-frontend/blob/master/src/api/ApiManager.ts#L178-L218

All of the updates you want to perform are in this method.

**Comment by drmrbrewer** [comment]
According to [this](https://caprover.com/docs/get-started.html#note-it-will-not-be-possible-to-carry-through-with-the-caprover-serversetup-if-youve-already-forced-https-on-your-caprover-instance):

> **Note: It will not be possible to carry through with the 'caprover serversetup' if you've already forced https on your CapRover instance.**
> In such case go straight to logging in with the caprover login command. To change the password go to the settings menu in the app.

In my case the default .htaccess does indeed redirect all http to https.  So it's not possible to run `caprover serversetup`?  Why is that?  And what does it mean by go straight to logging in with the `caprover login` command... without setting up the server first, is it possible to log in?  And is it possible to create an app (with a `caprover api` call) when the server is on https (particularly where the method is `POST`)?

**Comment by githubsaturn** [comment]
Two separate things here:

1- `.htaccess` ?? What is this for? CapRover doesn't use apache.

2- Regarding the api call: you cannot register the app and update the configs in one go. You have to first register the app. Wait a big and then update your config through calling `user/apps/appDefinitions/update` as mentioned in my comment above.

**Comment by drmrbrewer** [comment]
1. how true.  I have no idea what is forcing http to https then.  DNS for this domain is handled by cloudflare, and "always use https" is definitely off.
2. OK thanks.

**Comment by githubsaturn** [comment]
Try using a different root domain.

Also try experimenting to see if the issue is happening when you setup your server manually as well - or it's only happening when you're using the config file.

**Comment by drmrbrewer** [comment]
> try using a different root domain

yep, that works better with a different root domain.  I have literally no idea why the other root domain had a 302 redirect from http to https.  And I now see why letsencrypt was setting up a certificate... I am of course passing an email via `--certificateEmail`, and this is a required parameter so I can't not.  So it seems that https is mandatory on the caprover console.

Couple of remaining question:

First, after doing `caprover serversetup` (and before each subsequent `caprover api` call), it seems that I need to `caprover logout`, or else it complains.  It's not a big deal, but is there a way of avoiding this, and just taking the login credentials passed with the api call, without forcing a logout?

Secondly, usually I enable https on all apps that I create, but there doesn't seem to be a parameter for this in the [update path](https://github.com/caprover/caprover-frontend/blob/5e9eede7b19478fe5542262dc52150ab18b4d66c/src/api/ApiManager.ts#L178-L218)?    There is a `forceSsl` parameter but I assume that relates to the `Force HTTPS by redirecting all HTTP traffic to HTTPS` option on the app page rather than the `Enable HTTPS` button?  Is there any way of enabling https on the app via the api call?

**Comment by githubsaturn** [comment]
> (1) after doing caprover serversetup (and before each subsequent caprover api call), it seems that I need to caprover logout, or else it complains. It's not a big deal, but is there a way of avoiding this, and just taking the login credentials passed with the api call, without forcing a logout?

What is the error message? And what are the steps to repro the isse?

>(2) usually I enable https on all apps that I create, but there doesn't seem to be a parameter for this in the update path? There is a forceSsl parameter but I assume that relates to the Force HTTPS by redirecting all HTTP traffic to HTTPS option on the app page rather than the Enable HTTPS button? Is there any way of enabling https on the app via the api call?


There is `enableSslForCustomDomain` and `enableSslForBaseDomain` in the [ApiManager](https://github.com/caprover/caprover-frontend/blob/5e9eede7b19478fe5542262dc52150ab18b4d66c/src/api/ApiManager.ts#L16) class. All API calls are available there.


Regarding your 3rd issue:
It's not very clear to me how you're getting into that state. Basically what you're seeing should be applicable to "all serversetup calls". When you're using a different subdomain, it's a completely different domain in CapRover's view. Does the issue happen for a new domain as well? i.e. when:
- You spin up a new server
- You run `caprover serversetup --assumeYes ......` with a brand new domain / or subdomain?

Is there any change you're recycling your old IP and you have a caching layer in the middle?

**Comment by drmrbrewer** [comment]
Re (1):

> What is the error message? And what are the steps to repro the isse?

Actually it seems to be an info message and not an error message:

    # caprover serversetup --assumeYes --configFile config-server.json 
    ...
    # caprover api --configFile config-app-register.json

    Call generic CapRover API [Experimental Feature]...

    Ensuring authentication...

    Can't store store login credentials: https://captain.abc.mydomain.com already exist as abc in your currently logged in machines. If you want to replace the existing entry, you have to first use <logout> command, and then re-login.

    API call completed successfully!

    {}

So actually it seems that the call completes, so I can probably just ignore the message.

Re (2): thanks, I'll have a look at those.

Re (3):

> Does the issue happen for a new domain as well?

It seems to work the first time for a new domain (rather than subdomain), but for subsequent server setups (even with a different subdomain name) the issue happens again.

> Is there any change you're recycling your old IP and you have a caching layer in the middle?

Hmm, it's possible I suppose.  Well it definitely is the case that the cloud server provider keeps re-allocating the same IP address to me, each time I spin up a new server (at least for today).  DNS is handled by cloudflare, but the DNS entry is set to "DNS only" (not "Proxied") so I don't think there is any caching going on as such.  But I suppose that re-using the IP for the new server might still cause its own issues.  I would understand if it required a certain length of time to propagate, but the issue is solved by running `caprover serversetup` twice, rather than waiting any length of time.

**Comment by githubsaturn** [comment]
Your setup is a bit complex, but basically what you're describing could be reproducible by simply wiping the CapRover server and reinstalling CapRover. This is the steps that are equivalent to what you're doing:
- Create a brand new server
- Install CapRover on the server
- Run `caprover serversetup` on your local machine and setup your server
- At this point the server is working fine and you can deploy apps if you choose too
- Now [remove CapRover from the server completely](https://caprover.com/docs/troubleshooting.html#how-to-stop-and-remove-captain). 
- Reinstall CapRover on the server again.
- Try setting up your server by running `caprover serversetup` on your local machine
- At this point, you should observe the issue and get the 404 error.

Can you confirm if the issue is reproducible via running through these steps. If so, let's create a new issue with these exact repro steps and I'll look into it

**Comment by drmrbrewer** [comment]
After "remove and re-install CapRover", before running `caprover serversetup` using the same config file I have to `caprover logout`, but other than that, yes, the above steps do get me to the 404 error again.
