### ISSUE TITLE
How to use authenticate for repository that requires docker login?

### ISSUE THREAD

**Issue by berksonj** [caprover/caprover-cli#59]
I am trying to integrate the `caprover deploy --imageName` command into my CI/CD workflow.

However, I am getting the following message:
```
Deploy failed!
Error: (HTTP code 404) unexpected - pull access denied for xx/repox, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
I already logged in using the `docker login` command.

Please assist.

Thanks,
Jake

**Comment by githubsaturn** [comment]
You need to add credentials to your CapRover instance. Being logged in locally doesn't mean that CapRover can access the image. 

To log in to your private Docker repository on CapRover, do these steps:
- Navigate to CLUSTER
- Click on ADD REMOVE REGISTRY
- Enter your data and save your registry
- If you don't want your built images to be pushed to your private resgitry, under "Default Push Registry" section, click on the red text, and select DISABLED PUSH.
- Now you can use `caprover deploy --imageName` with a private image image.

**Comment by berksonj** [comment]
Thank you, maybe this should go in the docs somewhere?

**Comment by githubsaturn** [comment]
Usually things that are visible on the UI aren't document in details. But feel free to add it to the [docs](https://github.com/caprover/caprover-website/tree/master/docs)
