### ISSUE TITLE
missing git hash in deployment tab (and missing versions)

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-cli#6]
For some of my apps the git hash information is `n/a`:

![image](https://user-images.githubusercontent.com/9009792/52399120-203ea600-2ab3-11e9-8aed-86656cf57302.png)

Sure enough, in `/captain/data/config-captain.json` this information is missing too:

    "gitHash": ""

These are for versions deployed since upgrading to CapRover, incidentally.

Also, having [questioned recently](https://github.com/caprover/caprover/issues/359) whether it was really necessary to keep hundreds of version entries for each app, I now find that (since upgrading to CapRover) my config files have indeed now stripped the number of versions down to mostly three or four (or less) version entries per app!  The app I mentioned in the above post with 670+ version entries going back to the first deploy now only has two versions listed in the config file, the most recent of which doesn't even have `gitHash` information.

P.S. no I didn't manually edit the config to remove versions ;-)  And I should mention that I have `Keep most recent` (in Disk Cleanup) set to `2` but it's been that way for a long time, and some apps (e.g. the one screenshotted above) still has more than two version entries listed.

**Comment by githubsaturn** [comment]
Update to 1.1.1
```
npm i -g caprover
```

**Comment by drmrbrewer** [comment]
confirmed fixed :-)  thanks!
