### ISSUE TITLE
Exit command after finshing

### ISSUE THREAD

**Issue by ahmedmgh67** [caprover/caprover-cli#66]
When I run the "caprover setup" command with the -c flag and when it finishes I have to press enter to exit. It would be nicer if it exited automatically, especially that I'm using it in an automated script and I can't know when it finshes

**Comment by githubsaturn** [comment]
What environment you're running on? The noninteractive commands usually work bets in linux environment.

**Comment by ahmedmgh67** [comment]
@githubsaturn 
I'm running on ubuntu server 18.04 
I'm supplying it with a config.json but it still loads and when it finishes I have to press enter to exit.
I need to just work even in the background without any logs, is this possible?

**Comment by githubsaturn** [comment]
That's bizarre. I cannot reproduce the same issue on Ubuntu. If you want to run it in the background, you can just typical linux scripting techniques, like this one: https://unix.stackexchange.com/questions/74520/can-i-redirect-output-to-a-log-file-and-background-a-process-at-the-same-time

**Comment by ahmedmgh67** [comment]
I totally missed this, thanks a lot. I'm closing this issue now
