### ISSUE TITLE
running caprover outputs syntax error

### ISSUE THREAD

**Issue by tistudios** [caprover/caprover-cli#7]
caprover -h
/usr/local/lib/node_modules/caprover/built/utils/StdOutUtil.js:12
    printGreenMessage(message, exit = false) {
                                    ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/caprover/built/commands/caprover.js:7:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by tistudios** [comment]
Also running caprover by itself outputs this.
On Ubuntu 16.04 - Google Cloud VM
*.something.domain.com already set up. HTTPS enabled & forced.

**Comment by tistudios** [comment]
![screen shot 2019-02-07 at 11 43 15 pm](https://user-images.githubusercontent.com/39240982/52459262-24f66f00-2b32-11e9-863d-c7a18b92ff45.png)

**Comment by githubsaturn** [comment]
Your local node version must be really old (v4 probably). Update your local node.

https://github.com/caprover/caprover/issues/192#issuecomment-367746001

**Comment by githubsaturn** [comment]
Let me know if after updating your local NodeJS you still have problems. To check version of node you can run `node -v`

**Comment by githubsaturn** [comment]
I just added some warnings so that in the future, this is more self explanatory.
https://github.com/caprover/caprover-cli/commit/c6b8f7a071e9d987b14549721c0eb8f583f882d5

**Comment by tistudios** [comment]
Node version is v4.2.6. Don't know why I never noticed that before. I'll report

**Comment by tistudios** [comment]
Since I have already set up the caprover platform through the web interface, would I still need to run `caprover serversetup` or `caprover login` via terminal?

**Comment by tistudios** [comment]
Nevermind I ran `caprover login` and was able to login via terminal successfully! Thank you.

**Comment by githubsaturn** [comment]
No serversetup. Just login. Only if you want to deploy via CLI. It's not the only way to deploy.
