### ISSUE TITLE
Can't remove server if enter wrong password during setup

### ISSUE THREAD

**Issue by diego-vieira** [caprover/caprover-cli#73]
- Run `caprover serversetup`
- `? have you already started CapRover container on your server? Yes`
- `? IP address of your server: [your server ip]`
- `? CapRover server root domain: any.domain.com`
- `? new CapRover password (min 8 characters): [hidden]` << here, enter 12345678
- `? enter new CapRover password again: [input is hidden]` << here, enter a different password

You will get `>> Passwords do not match.`.

At this point, I would expect the input to return to `new CapRover`, however, it doesn't. Then you have to press `CTRL+C`.

If you try to setup `127.0.0.1` you get `You may have already setup the server with root domain: caprover.wtsoftware.com.br! Use caprover login to log into an existing server.`

Even if you `caprover logout` there is no way to remove the server from the config.

**Comment by githubsaturn** [comment]
> Even if you caprover logout there is no way to remove the server from the config.

What do you mean by "remove the server from the config" ?

If you enter a wrong password during setup, all you need to do is to do a `caprover logout` and make sure that your server does not exist in the list. If it does, just log out from CLI and try `caprover serversetup` again.

At some point during setup, the process cannot start from the scratch. If you face such situation, simply:
- Go you `captain.root.domain.com` and log in using `captain42` (default password), or the password you chose during setup.
- Enable HTTPS and Force HTTPS from the dashboard
- Last, simply go to settings, and update your password after you have enabled HTTPS to ensure that your password is safe


Then using CLI, just run `caprover login`


Let me know if you still have problems.

**Comment by diego-vieira** [comment]
@githubsaturn 

`Enable HTTPS and Force HTTPS from the dashboard`

Many thanks!
