### ISSUE TITLE
Update Caprover using CLI?

### ISSUE THREAD

**Issue by thepandaguitar** [caprover/caprover-cli#77]
Hi,

I'm spinning many Caprover droplets on DigitalOcean, and it's asking me to update to the latest version.

<img width="666" alt="Screen Shot 2021-01-28 at 16 59 41" src="https://user-images.githubusercontent.com/3105613/106107482-5555ce80-618a-11eb-9a0e-f3c15ba482b3.png">

I'd like to enjoy the latest and greatest of Caprover. So I have a few ways of going about this:

- Is it possible to update my Caprover instances using the CLI? 
- Are there any plans to update the Caprover image on DO?
- Maybe it's best to update it myself and spin up snapshots?

Problem with the other workarounds is they only make sense for new instances. I would still have to update the existing instances at some point.

Any help would be appreciated. Thank you very much.

**Comment by githubsaturn** [comment]
Unfortunately the DO images must be manually updated. Even if you spin up a DO docker one click image, it still needs to be updated. This manual update process is a bit time consuming and we only update the DO image every few months.

Having said that, installing CapRover is actually super easy!To install the latest version of CapRover on a DO image, here is the process that I suggest
- Spin up a DO with Docker and Ubuntu 18 (DO NOT Use Ubuntu 20)
- Run this script when the instance is ready:
```
apt update && apt full-upgrade -y

ufw allow 80,443,3000,996,7946,4789,2377/tcp; ufw allow 7946,4789,2377/udp;

docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```

That's it! Just a simple copy and paste!

**Comment by thepandaguitar** [comment]
Unfortunately DO only offers 1-click Docker on Ubuntu 20.  Since CLI updates are not yet supported, I guess I'll have to go the manual update route for now.

Thank you very much for the quick and helpful response @githubsaturn!

**Comment by githubsaturn** [comment]
Alternatively you can setup DO with CapRover, then before running `caprover setup` , run these on your server:

```
apt update && apt full-upgrade -y

docker pull caprover/caprover:latest

docker service update --image caprover/caprover:latest captain--captain
```
