### ISSUE TITLE
Where is CapRover data stored?

### ISSUE THREAD

**Issue by nixilb** [caprover/caprover-cli#79]
C:\Users\nisju\Downloads\node\node>caprover serversetup
Setup CapRover machine on your server...

? have you already started CapRover container on your server? Yes
? IP address of your server: xxx.XXX.XXX.XXX

You may have already setup the server with root domain: mydn.com! Use caprover login to log into an existing server.

Where is that info stored?

**Comment by githubsaturn** [comment]
> You may have already setup the server with root domain: mydn.com! Use caprover login to log into an existing server.

This message does not come from local storage. It comes from the fact that a request to HTTP://IP:3000 gets redirected to HTTPS.

You can follow the guide and just use `caprover login`.


If you want to reinstall CapRover on a server, you can follow [these instructions to uninstall](https://caprover.com/docs/troubleshooting.html#how-to-stop-and-remove-captain), then reinstall normally.
