### ISSUE TITLE
Return valid JSON for API commands

### ISSUE THREAD

**Issue by thepandaguitar** [caprover/caprover-cli#80]
Hi @githubsaturn,

I want to update the Container HTTP Port using API. I noticed that you need to send the whole app definition in order to do that. However, getting the app definition using `caprover api` returns text which is not convenient for using the data in subsequent calls.

<img width="770" alt="Screen Shot 2021-01-29 at 15 22 18" src="https://user-images.githubusercontent.com/3105613/106239531-1e44f300-6246-11eb-96dc-7e80e99789aa.png">

- For the `api` command in particular, I think it makes more sense to have it return valid JSON. Do you think this is a possible change?

- I am still not very familiar with the API yet, so before I do any parsing, I want to ask you if you have any ideas on how to update Container HTTP Ports?

Thank you @githubsaturn!

**Comment by githubsaturn** [comment]
You can specify the output to be a file:
```
CAPROVER_CONFIG_FILE='./config.json' caprover api -o output.json
```

If you do this, you only get the json response in the file

**Comment by thepandaguitar** [comment]
@githubsaturn Fantastic! Thank you so much for your help 💯

**Comment by thepandaguitar** [comment]
@githubsaturn, sorry to ask another question. I would like to confirm with you if there are required fields when updating the app definitions. 

AFAIK, I could update the HTTP Container Port just by posting this data, and everything is working fine.
`{"appName":"search","instanceCount":1, "containerHttpPort":7700}`

Just want to make sure it doesn't break somewhere else.
Do you have defaults set somewhere?

**Comment by thepandaguitar** [comment]
@githubsaturn, sorry to ask another question. I would like to confirm with you if there are required fields when updating the app definitions. 

AFAIK, I could update the HTTP Container Port just by posting this data, and everything is working fine.
`{"appName":"myapp","instanceCount":1, "containerHttpPort":80}`

Just want to make sure it doesn't break somewhere else.
Do you have defaults set somewhere?
