### ISSUE TITLE
Too many certificates already issued

### ISSUE THREAD

**Issue by thepandaguitar** [caprover/caprover-cli#82]
Hi @githubsaturn,

Is Caprover not using wildcard multi-domain certificates? I am getting the following error:

```
There were too many requests of a given type :: Error creating new order :: too many certificates already issued for {{mysite}} - see https://letsencrypt.org/docs/rate-limits/
```

Unfortunately this would be a deal breaker and make the project unsuitable for deploying many apps.

Any workarounds?

**Comment by githubsaturn** [comment]
> Is Caprover not using wildcard multi-domain certificates? I am getting the following error:

No. wildcard certificate requites hooking into your DNS server. CapRover is not a DNS server.

> Any workarounds?

You can manually obtain the cert and use the `nginx-shared` directory to manually edit the nginx config to load your custom cert.

**Comment by thepandaguitar** [comment]
@githubsaturn where can I find this folder?

**Comment by githubsaturn** [comment]
https://caprover.com/docs/nginx-customization.html#custom-files-and-directories

**Comment by thepandaguitar** [comment]
@githubsaturn you thought of everything, this is life saving. I love this project! 💯
I got a wildcard cert and set up the custom configs. Works like a charm.

What about renewals - does Caprover do it for custom configs? Or, do I renew my cert and place it again in 3 months in the `nginx-shared` directory?

**Comment by githubsaturn** [comment]
> What about renewals

CapRover runs renewal only for certs that are issued using `captain-certbot`. You'd have to manually renew and replace your custom certs.

> I am currently sending custom nginx config for each individual app. There's a way to do custom nginx config in the Settings tab, is that for Caprover itself or can it update all the app configs at once?

The one in settings is for CapRover itself, there is currently a feature request to make the default configurable:
https://github.com/caprover/caprover/issues/977
