### ISSUE TITLE
Is there a limit to the number of apps?

### ISSUE THREAD

**Issue by thepandaguitar** [caprover/caprover-cli#83]
Hi @githubsaturn,

- Are there any hard limits on the number of apps I can deploy with 1 instance of Caprover? Maybe a limit before Caprover performance drops / starts acting out?
- Do you see any difference between beefing up the main machine specs, and adding more nodes instead?

AFAIK Caprover is an abstraction for Docker Swarm so I'm not aware of any limits, but I'd like to get your thoughts on this, should I face any issues down the line.

Thank you as always!

**Comment by githubsaturn** [comment]
CapRover doesn't impose any particular limit on the number of apps. But default docker network config that CapRover uses allows for 254 containers.

**Comment by thepandaguitar** [comment]
@githubsaturn - what if I got rid of the networks settings below for each app, would I still be constrained by 254 containers?

```
networks:
      - captain-overlay-network
```

Alternatively, is there a way to add a new network `captain-overlay-myNetwork`?

**Comment by githubsaturn** [comment]
Adding a new network requires using [manual overrides](https://caprover.com/docs/service-update-override.html) which are not straightforward.

Plus, CapRover uses a simply JSON as the database and it's not really designed to work with a very high number of apps. There is not theoretical limit, but it's just not optimal.
