### ISSUE TITLE
How deploy works is not clear.

### ISSUE THREAD

**Issue by nixilb** [caprover/caprover-cli#86]
Does it upload all the folder (as it is done in a maven deploy) ?
What is uploaded?: only the git address (and captain def file) and a git pull is done on the server?

I don't understand why it asks me the git branch name. This point does not appear in the documentation.
Is it mandatory that the code is git managed?

**Comment by githubsaturn** [comment]
It uses git command to create your archived version of your particular branch in .tar format. Then it uploads it to the server and cleans up the tar file.

**Comment by nixilb** [comment]
Clear.

**Comment by nixilb** [comment]
This means that "caprover deploy" from a console in a directory does NOT deploy that directory (but the clouded git version of):

Example 1
------------
- download php sample
- remove the content except the .git folder
- add any HTML stuff
- make a caprover deploy from this 

Result: the old removed php sample is deployed instead of the new HTML stuff

Example 2
------------
- download php sample
- make any modification
- make a caprover deploy from this 

Result: the modification is not uploaded

**Comment by nixilb** [comment]
No idea about the problems depicted above? Are the example true?

**Comment by githubsaturn** [comment]
Correct.
CapRover uses `git archive` to create your build content. It doesn't use the "cloud" (remote) version of your git repo. It uses the latest commit on your local branch.

You can manually run `git archive --format tar --output ./somefile` to see what is sent to CapRover to build.
