### ISSUE TITLE
Which captain-definition file for J2EE app?

### ISSUE THREAD

**Issue by nixilb** [caprover/caprover-cli#89]

**Comment by githubsaturn** [comment]
Your need to create your own dockerfile. There's no template id for java. 

Just search for "dockerfile j2ee app". 

Alternatively you can ask on our slack channel to see if anyone has a template.

**Comment by nixilb** [comment]
I already have a dockerfile with  tomcat inside that HTTP-publishes a docker volume. Can I use it? Is there any modification I have to add?

**Comment by githubsaturn** [comment]
HTTP-publishes a docker volume? Not sure what this means. But in general, yes, no modifications needed for your Dockerfile. CapRover just runs a `docker build` on your repo.
