### ISSUE TITLE
Creating a new app from CLI?

### ISSUE THREAD

**Issue by Wrapperup** [caprover/caprover-cli#90]
Hi, I think a proper "create app" command would be great to have. Heroku does this semi-automatically when you deploy your app. I think for caprover, adding an extra parameter in the deploy command would suffice. Maybe another command? I think both would be useful.

I realize you can do this through the `caprover api` command, though that isn't very handy to be fair.

I would like to make a PR to add this if such a feature is wanted & doesn't exist.

**Comment by githubsaturn** [comment]
It's intentional that we don't reflect all API functionality via CLI. It's done to reduce the maintenance cost.

Having said that, `caprover api` is exposing all these functionalities for users who want to utilize other APIs.

See here for example: https://github.com/caprover/caprover-cli/issues/55
