### ISSUE TITLE
`caprover deploy --default` hangs at the: `Ensuring authentication...` step

### ISSUE THREAD

**Issue by neil-rubens** [caprover/caprover-cli#94]
`caprover deploy`  works fine; 

but when I try to use :
`caprover deploy --default` 

it hangs at the: 
`Ensuring authentication...`

p.s. ❤️ using caprover

**Comment by githubsaturn** [comment]
Duplicate of https://github.com/caprover/caprover-cli/issues/36

Looks like it's only a windows problem.

**Comment by neil-rubens** [comment]
> Looks like it's only a windows problem.

Indeed, am on Windows 10.
